import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderSearchBar } from "./components/searchBar";
import { Banner } from "./components/banner";
import { Container, Box } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: "flex" }} width={'100vw'} overflow={'auto'}>
          <CssBaseline />
          <HeaderSearchBar/>
          <Container component="main" sx={{ p: 3, marginTop:'5vh', height:'100vh'}} >
          <Banner />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          </Container>
        </Box>
      </body>
    </html>
  );
}
