external:
    api: https://finnhub.io/api/v1/
    token: cm26o1pr01qvesfhho3gcm26o1pr01qvesfhho40
spring:
    kafka:
        bootstrap-servers: localhost:19092
        group-Id-stock-info-db: group-stock-info-db
        group-Id-stock-info-fe: group-stock-info-fe
        group-Id-stock-price-db: group-stock-price-db
        group-Id-stock-price-fe: group-stock-price-fe
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true
        path: /h2-console

#    codec:
#        max-in-memory-size: 10MB

topics:
    symbols:
        US: topic_symbols_US
        CA: topic_symbols_CA
    stock: topic_allstock
    webSocket:
        ws-symbols-fe: /bff/symbols
        ws-prices-fe: /bff/prices