auth:
  baseurl: tbd
  login:
    endpoint: tbd

spring:
  application:
    name: account-security
  datasource:
    url: jdbc:h2:mem:accountdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    path: /h2-console
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 40841952048-8t8fjmrgkqoa0votm5t3jf80j4ccj202.apps.googleusercontent.com
#            client-secret: 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